# This file was generated by GoReleaser. DO NOT EDIT.
cask "truestamp-cli" do
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/truestamp/truestamp-cli/releases/download/v#{version}/truestamp-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "766f3a023e96379e6b96540b465dbcbe2acfd135ff0a800480abacecda76fb22"
    end
    on_arm do
      url "https://github.com/truestamp/truestamp-cli/releases/download/v#{version}/truestamp-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "a1666f33be7279c33dd0921ed904196d0fa45829ee57632168f2b2a963b89b6d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/truestamp/truestamp-cli/releases/download/v#{version}/truestamp-cli_#{version}_linux_amd64.tar.gz"
      sha256 "b399a075a1e7e98492237add65699f52525b7472dbcadf3d7dd2ad13c57fc114"
    end
    on_arm do
      url "https://github.com/truestamp/truestamp-cli/releases/download/v#{version}/truestamp-cli_#{version}_linux_arm64.tar.gz"
      sha256 "9f2dae79e52f2e567b78892436634730a990fa3dc972a2bdaf0621e0fcbb275d"
    end
  end

  name "truestamp-cli"
  desc "Truestamp CLI — tools for cryptographic timestamping"
  homepage "https://truestamp.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "truestamp"

  # No zap stanza required

  caveats <<~EOS
    The truestamp binary is not yet signed with an Apple Developer ID,
    so macOS Gatekeeper will block it on first run ("truestamp" Not
    Opened). Clear the quarantine attribute once after install or
    upgrade to avoid the prompt:

      xattr -cr #{staged_path}

    (Signed and notarised builds are on the roadmap.)
  EOS
end
